var url = require("url")
var path = require("path")
var Stream = require("stream")

module.exports = {
  version: Boolean,
  loglevel: ["silent", "win", "error", "warn", "info", "verbose", "silly"],
  registry: url,
  color: ["always", Boolean],
  logfd: [Number, Stream],

  aoa: Array,
  nullstream: [null, Stream],
  date: Date,
  str: String,
  browser: String,
  cache: path,
  depth: Number,
  description: Boolean,
  dev: Boolean,
  editor: path,
  force: Boolean,
  global: Boolean,
  globalconfig: path,
  group: [String, Number],
  gzipbin: String,
  long: Boolean,
  "node-version": [false, String],
  npaturl: url,
  npat: Boolean,
  "onload-script": [false, String],
  outfd: [Number, Stream],
  parseable: Boolean,
  pre: Boolean,
  prefix: path,
  proxy: url,
  "rebuild-bundle": Boolean,
  searchopts: String,
  searchexclude: [null, String],
  shell: path,
  t: [Array, String],
  tag: String,
  tar: String,
  tmp: path,
  "unsafe-perm": Boolean,
  usage: Boolean,
  user: String,
  username: String,
  userconfig: path,
  viewer: path,
  _exit: Boolean,
  path: path
}